### ISSUE TITLE
How to send authorization header?

### ISSUE THREAD

**Issue by csharad** [nuxt-community/apollo-module#112]
I am not able to do authorization requests. Doing as written in https://www.apollographql.com/docs/react/recipes/authentication.html also does not work. I wrote the following in nuxt config.
```
apollo: {
    includeNodeModules: true,
    clientConfigs: {
      default: {
        httpEndpoint: 'http://localhost:3000/graphql',
        link: new HttpLink({
          uri: '/graphql',
          credentials: 'same-origin',
          fetch
        })
      }
    }
  },
```

 It throws the following stack trace:
```
{ TypeError: Cannot read property 'length' of undefined
    at isTerminating (/mnt/dev/theshortcentral/tsc-editor/node_modules/apollo-link/lib/bundle.umd.js:53:29)
    at concat (/mnt/dev/theshortcentral/tsc-editor/node_modules/apollo-link/lib/bundle.umd.js:175:13)
    at ApolloLink.concat (/mnt/dev/theshortcentral/tsc-editor/node_modules/apollo-link/lib/bundle.umd.js:198:20)
    at createApolloClient (node_modules/vue-cli-plugin-apollo/graphql-client/dist/index.js:67:0)
    at module.exports.__webpack_exports__.a (.nuxt/apollo-module.js:45:0)
    at createApp (.nuxt/index.js:137:0)
    at process._tickCallback (internal/process/next_tick.js:68:7) statusCode: 500, name: 'TypeError' }

```

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c94">#c94</a>)</em></sub></div>

**Comment by dohomi** [comment]
@csharad you don't need to provide a link. Make sure that the tokenName fits to your application logic - all you need to do is calling 
```
this.$apolloHelpers.onLogin(token) 
```
as described here: https://github.com/nuxt-community/apollo-module#build-in-methods

**Comment by csharad** [comment]
@dohomi I was already doing that but it was still not working. I scanned through your code and saw that authorization uses `Bearer` whereas mine uses `Basic`. So, I had to workaround my code to make it work.
It would be helpful, if there was an option to set the authorization scheme.

**Comment by dohomi** [comment]
@csharad feel free to add a PR for your usecase, I can review it soon and add it to v4
