### ISSUE TITLE
Cannot find module 'es6-promise/auto'

### ISSUE THREAD

**Issue by jon-ht** [nuxt-community/apollo-module#137]
### Version

[v4.0.0-rc.1](https://github.com/apollo-module/releases/tag/v4.0.0-rc.1)

### Reproduction link

[https://github.com/jon-ht/dnc-pwa](https://github.com/jon-ht/dnc-pwa)

### Steps to reproduce

```
$ npm install # Or yarn install

$ npm run dev
```

Open http://localhost:3000

If you comment `@nuxtjs/apollo` under `nuxt.config.js` modules, it all works as expected

### What is expected ?

Default page should show up

### What is actually happening?

Console logs :

```
  nuxt:render Rendering url / +0ms
{ Error: Cannot find module 'es6-promise/auto' from 'P:\wamp64\www\dnc-pwa'
    at Function.module.exports [as sync] (P:\wamp64\www\dnc-pwa\node_modules\resolve\lib\sync.js:43:15)
    at r (P:\wamp64\www\dnc-pwa\node_modules\vue-server-renderer\build.js:8332:44)
    at Object.<anonymous> (server-bundle.js:1730:18)
    at __webpack_require__ (webpack:/webpack/bootstrap 7b32f49b9a66c9f5156c:25:0)
    at Object.<anonymous> (.nuxt/index.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 7b32f49b9a66c9f5156c:25:0)
    at Object.<anonymous> (.nuxt/server.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 7b32f49b9a66c9f5156c:25:0)
    at server-bundle.js:92:18
    at Object.<anonymous> (server-bundle.js:95:10)
    at evaluateModule (P:\wamp64\www\dnc-pwa\node_modules\vue-server-renderer\build.js:8338:21)
    at P:\wamp64\www\dnc-pwa\node_modules\vue-server-renderer\build.js:8396:18
    at new Promise (<anonymous>)
    at P:\wamp64\www\dnc-pwa\node_modules\vue-server-renderer\build.js:8388:14
    at Object.renderToString (P:\wamp64\www\dnc-pwa\node_modules\vue-server-renderer\build.js:8564:9)
    at Renderer.renderRoute (P:\wamp64\www\dnc-pwa\node_modules\nuxt\lib\core\renderer.js:344:41)
  code: 'MODULE_NOT_FOUND',
  statusCode: 500,
  name: 'NuxtServerError' }
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c121">#c121</a>)</em></sub></div>

**Comment by dohomi** [comment]
this seems unrelevant to this package. did you re-run npm install or npm update?

**Comment by jon-ht** [comment]
Yes, I did. I've tried on several projects and each time I activate `@nuxtjs/apollo`, build fails but not always with this error.

For example, if i create a project based on https://github.com/vuetifyjs/nuxt and I add `@nuxtjs/apollo`, then stylus loader fails resolving imports in `.styl` files.

I could give you an exception trace for this case if needed

**Comment by jon-ht** [comment]
@dohomi Thanks ! It seems to work when manually adding `npm i es6-promise`, with or without `@nuxtjs/pwa` enabled

**Comment by luis-rocha** [comment]
I get the same issue, but I don't even get to rendering. When I add @nuxtjs/apollo to nuxt.config.js, I would get a Nuxt error
`TypeError: Cannot convert undefined or null to object`
So after reading this thread, I added es6-promise, and the above error went away, and I get a line that says `DONE  Compiled successfully in -10314ms`, but...the page still doesn't load, and I don't get the line that says `OPEN  http://localhost:3000` and on the browser, I then get `Cannot GET /performanceAppraisal/submit/1`
So, at least for me, adding @nuxtjs/apollo continues breaking Nuxt, and I can't find a good way to add any apollo client to Nuxt :(

**Comment by dohomi** [comment]
please check most recent version of this module. Will close it for now
