### ISSUE TITLE
Apollo module brakes transpiling of 3rd party libraries

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/apollo-module#140]
### Version

[v4.0.0-rc.1](https://github.com/apollo-module/releases/tag/v4.0.0-rc.1)

### Reproduction link

[https://github.com/AndrewBogdanovTSS/nuxt-bt-vue-apollo](https://github.com/AndrewBogdanovTSS/nuxt-bt-vue-apollo)

### Steps to reproduce

- Add Bootstrap-Vue dependencie
- Create a bt-vue plugin to only include specific components
- Add @nuxt/apollo plugin
- Connect apollo module in nuxt.config.js
- npm run dev

### What is expected ?

Bootstrap Vue library is building from it's source code due to Nuxt 2 new  `transpile` property that exists in nuxt config

### What is actually happening?

```
× error F:\Projects\Study\Nuxt\nuxt-bt-vue-apollo\node_modules\bootstrap-vue\es\components\button\index.js:1
  (function (exports, require, module, __filename, __dirname) { import bButton from './button';
  ^^^^^^
  
  SyntaxError: Unexpected token import
  at createScript (vm.js:80:10)
  at Object.runInThisContext (vm.js:139:10)
  at Module._compile (module.js:616:28)
  at Object.Module._extensions..js (module.js:663:10)
  at Module.load (module.js:565:32)
  at tryModuleLoad (module.js:505:12)
  at Function.Module._load (module.js:497:3)
  at Module.require (module.js:596:17)
  at require (internal/module.js:11:18)
  at r (F:\Projects\Study\Nuxt\nuxt-bt-vue-apollo\node_modules\vue-server-renderer\build.js:8341:16)
  at Object.bootstrap-vue/es/components/button (server-bundle.js:2963:18)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Module../plugins/bootstrap-vue.js (plugins/bootstrap-vue.js:1:0)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Module../.nuxt/index.js (.nuxt/index.js:1:0)
  at __webpack_require__ (webpack/bootstrap:25:0)
```

### Additional comments?

This error is happening only once apollo module is connected to the project. It seems like nuxt/apollo overrides transpile property in is some way that prevents it from working properly.
cc: @dohomi 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c125">#c125</a>)</em></sub></div>

**Comment by dohomi** [comment]
Can check if this PR fixes the issue: https://github.com/nuxt-community/apollo-module/pull/158

**Comment by Somtom** [comment]
I think I have a similar problem (same Version)

Adding `@nuxt.js/apollo` to the modules leads to this error:

```
nuxt:render Rendering url /_nuxt/0b19f33e74b584fae71e.hot-update.json +0ms
{ /PATH/TO/MY/NUXT/APP/node_modules/buefy/src/components/snackbar/Snackbar.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                              ^

SyntaxError: Unexpected token <
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
...
```

Only removing the `@nuxt.js/apollo` from modules, without doing anything else, prevents that error.

**Comment by dohomi** [comment]
please check with most recent version rc3

**Comment by dohomi** [comment]
closing this now. Should be fixed with either rc3 or rc2.2. Feel free to reopen
