### ISSUE TITLE
Option for separate endpoints for server and client

### ISSUE THREAD

**Issue by chriscalo** [nuxt-community/apollo-module#272]
### What problem does this feature solve?

When running locally, the Apollo client on the server and in the browser can both use `http://localhost:8000/graphql` (or whatever the port is) as the `httpEndpoint` and everything works fine:

``` js
export default {
  apollo: {
    clientConfigs: {
      default: {
        httpEndpoint: `http://${HOST}:${PORT}/graphql`,
      },
    },
  },
}
```

However, when deployed to production (or any other non-local environment), the server can use `http://localhost:8000/graphql`, but the browser definitely cannot. The simplest solution in my case is for the client value to be just `/graphql`, and the browser will assume the same domain and port as the currently-running page.

Both [`@nuxtjs/axios`][@nuxtjs/axios] and [`@nuxt/http`][@nuxt/http] have separate options for the server (`baseURL`) and the browser (`browserBaseURL`). It seems the Apollo module needs the same to support anyone writing an app where their UI and API are running on the same server. (Unless I missed something. Apollo seems to assume that the API is running on a different server.)

[@nuxtjs/axios]: https://axios.nuxtjs.org/options
[@nuxt/http]: https://http.nuxtjs.org/api/

I tried the following workaround in `nuxt.config.js` of using multiple Apollo clients, but I wasn't able to get it working:

``` js
export default {
  modules: [
    "@nuxtjs/apollo",
  ],
  apollo: {
    clientConfigs: {
      default: {
        httpEndpoint: "localhost:8000/graphql",
      },
      browser: {
        httpEndpoint: "/graphql",
      },
    },
  },
};
```

I tried putting the following in every Vue component to dynamically select the right client based on the environment, but got errors in the browser:

``` html
<script>
  export default {
    apollo: {
      $client: typeof window === "undefined" ? "default" : "browser",
      // ...
    },
  };
</script>
```

### What does the proposed changes look like?

In `nuxt.config.js`, just like for the [`@nuxtjs/axios`][@nuxtjs/axios] and [`@nuxt/http`][@nuxt/http] modules, the Apollo module should support separate endpoint values for server and client:

``` js
export default {
  modules: [
    "@nuxtjs/apollo",
  ],
  apollo: {
    clientConfigs: {
      default: {
        httpEndpoint: "localhost:8000/graphql",
        browserHttpEndpoint: "/graphql",
      },
    },
  },
};
```

[@nuxtjs/axios]: https://axios.nuxtjs.org/options
[@nuxt/http]: https://http.nuxtjs.org/api/

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c252">#c252</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
That makes scene, I usually attach a domain for production graphql server, so never face this. I'll make a update on this.

**Comment by chriscalo** [comment]
Thanks so much for adding this 🙏

---

I’m curious how this will work.

If you only supply `httpEndpoint` and not `browserHttpEndpoint`, will it affect `browserHttpEndpoint`? 

It would be great if `@nuxtjs/apollo` matched the behavior of `@nuxtjs/axios` and `@nuxt/http` in this regard, which is to keep the two config options entirely separate (setting one doesn't affect the other).

Thanks again.

**Comment by kieusonlam** [comment]
I can tell that it's same behavior as `@nuxtjs/axios`
https://github.com/nuxt-community/axios-module/blob/b9335b1c55b3af34e2d6e5897fedb8372a620ce4/lib/plugin.js#L160

`browserBaseURL` is just a simple replacing baseURL in client side.

I think you also can do the same without `browserHttpEndpoint`:

Example `nuxt.config.js`
```js
export default {
  modules: [
    "@nuxtjs/apollo",
  ],
  apollo: {
    clientConfigs: {
      default: {
        httpEndpoint: process.server
            ? "http://localhost:8000/graphql",
            : "/graphql"
      },
    },
  },
};
```
It's should work the same as this PR https://github.com/nuxt-community/apollo-module/pull/275 . I haven't test them yet, so it would be great if you can do some test on them.

**Comment by chriscalo** [comment]
I will check tomorrow, but I'm pretty sure `process.server` and `process.client` are undefined inside of `nuxt.config.js`. This is the first path I tried.

Some config options (but not all as far as I can tell) accept functions that return a config object and are passed values like `isServer` and `isClient`, but I couldn't figure out whether there's a way to make that work for the `apollo` config.

**Comment by chriscalo** [comment]
And I misunderstood how the axios and http options worked. Thanks for the link. 👍

**Comment by chriscalo** [comment]
Indeed, this works as I remembered.

I tried adding the following to my `nuxt.config.js`:

``` js
console.log(`process.server = ${process.server}`);
console.log(`process.client = ${process.client}`);

export default {
  modules: [
    "@nuxtjs/apollo",
  ],
  apollo: {
    clientConfigs: {
      default: {
        httpEndpoint: (() => {
          if (process.server) return "http://localhost:8000/graphql";
          if (process.client) return "/graphql";
          throw new Error("Both process.server and process.client are falsy");
        })(),
      },
    },
  },
};
```

I get the following output when I run the build:

``` text
process.server = undefined
process.client = undefined
/Users/ccalo/Projects/viaticus/nuxt.config.js:1
Error: Both process.server and process.client are falsy
    at require.apollo.clientConfigs.default.httpEndpoint (/Users/ccalo/Projects/viaticus/nuxt.config.js:42:17)
    at Object.<anonymous> (/Users/ccalo/Projects/viaticus/nuxt.config.js:43:11)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/Users/ccalo/Projects/viaticus/server/nuxt.js:1)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/Users/ccalo/Projects/viaticus/server/index.js:1)
    at Generator.next (<anonymous>)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[ERROR] 09:00:43 Error
```

This seems like a design flaw in Nuxt, but there might be good reason why this doesn't work.

**Comment by chriscalo** [comment]
Filed a [feature request](https://github.com/nuxt/nuxt.js/issues/6629) with `nuxt.js`

**Comment by chriscalo** [comment]
Using the separate `apollo-config.js` file did seem to successfully build (thanks for pointing out that option), but it looks like it caused different client-side issues, so I'm happy `browserHttpEndpoint` is now an option 👍

**Comment by Markus357** [comment]
Same issue here - `browserHttpEndpoint` appeared to not be working for me until I upgraded the apollo-module from version `4.0.0-rc4` to `4.0.0-rc19`. Looks like it was introduced in `4.0.0-rc.17`

**Comment by wiese** [comment]
FTR this was implemented in #275 and [documented](https://github.com/nuxt-community/apollo-module/commit/800038215bd449d3f66ace886f733fa8df877ebc#diff-04c6e90faac2675aa89e2176d2eec7d8R90) in #277.

**Comment by HDxXxHD** [comment]
In apollo-config.js

```
httpEndpoint: (() => {
        if (process.server) return "http://[::1]:8000/graphql";
        if (process.client) return "http://[::1]:8000/graphql";
        throw new Error("Both process.server and process.client are false");
      })(),
```
It works.
