### ISSUE TITLE
HTTP link & WS using pusher API (error: Hostname/IP does not match certificate's altnames)

### ISSUE THREAD

**Issue by stephenjason89** [nuxt-community/apollo-module#355]
Hello, my graphql endpoint uses pusher api so i create my apollo link as shown below. 

```
import Pusher from 'pusher-js'
import { InMemoryCache } from 'apollo-cache-inmemory'
import { ApolloLink } from 'apollo-link'
import { HttpLink } from 'apollo-link-http'
import PusherLink from './pusher'

export default (context) => {
    const httpLink = new HttpLink({
        uri: context.$config.appUrl + context.$config.publicApi + '/graphql',
    })
    const pusherLink = new PusherLink({
        pusher: new Pusher(context.$config.pusherKey, {
            wsHost: context.$config.wsHostname,
            wsPort: context.$config.wsPort,
            wssPort: context.$config.wsPort,
            disableStats: true,
            authEndpoint: context.$config.appUrl + context.$config.publicApi + '/graphql/subscriptions/auth',
            enabledTransports: ['ws', 'wss'],
        }),
    })
    const link = ApolloLink.from([pusherLink, httpLink])

    return {
        link,
        cache: new InMemoryCache(),
        getAuth: () => 'Bearer SAMPLETOKENasjkdkjahsdkhkashdkjahsdkhkashdkhasdjhajsd',
        defaultHttpLink: false,
    }
}

```

This is works but will fail eventually it randomly throws me this error, 

```
FetchError: request to https://ip-172-31-37-137.ap-southeast-1.compute.internal/api/graphql failed, reason: Hostname/IP does not match certificate's altnames: Host: ip-172-31-37-137.ap-southeast-1.compute.internal. is not in the cert's altnames: DNS:foodat.ph
    at ClientRequest.<anonymous> (/var/www/html/foodat-nuxt/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ERR_TLS_CERT_ALTNAME_INVALID',
  code: 'ERR_TLS_CERT_ALTNAME_INVALID'
}
```

sometimes, it will last for a day and other times for a few hours before i encounter this error.
My server set up is
graphql-server and node server -> nginx -> cloudflare

nginx have a simple rule that redirects all /api/ traffic to graphql-server and all / traffic to node server(nuxt)

I use pm2 to keep my my node server running but because of this random error about ```Hostname/IP does not match certificate's altnames``` I get a very high cpu usage when pm2 tries to restart it due to failing on that error.

If someone can please point me in the right direction.

Thank you

**Comment by stephenjason89** [comment]
I have found that nuxt on the server side is keeping every websocket connection alive. I can see it in my websocket server that after running a siege, all connections to websocket is still there.

**Comment by stephenjason89** [comment]
How do I do the websocket connection on the client side only?
