### ISSUE TITLE
Vercel – Nuxt Internal Server Error

### ISSUE THREAD

**Issue by oritwoen** [nuxt-community/apollo-module#393]
### Version

[v4.0.1-rc.1](https://github.com/apollo-module/releases/tag/v4.0.1-rc.1)

### Reproduction link

Don't have.

### Steps to reproduce

Use package @nuxtjs/vercel-builder and  @nuxtjs/apollo to run Nuxt with Vercel.

### What is expected ?

Clean run without problems.

### What is actually happening?

[GET] /
20:18:39:58
Error Network error: Expected signal to be an instanceof AbortSignalError Network error: Expected signal to be an instanceof AbortSignal ERROR  Network error: Expected signal to be an instanceof AbortSignal  at new ApolloError (node_modules_dev/apollo-client/bundle.umd.js:92:0)  at server.js:48937:34  at server.js:49357:15  at Set.forEach (<anonymous>)  at server.js:49355:26  at Map.forEach (<anonymous>)  at QueryManager.broadcastQueries (node_modules_dev/apollo-client/bundle.umd.js:2004:0)  at server.js:48832:29

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c378">#c378</a>)</em></sub></div>

**Comment by paulmelero** [comment]
See https://github.com/nuxt/vercel-builder/issues/509 just in case ;)

**Comment by alaa19090** [comment]
See nuxt/vercel-builder/issues/805 worked for me
