### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by erik-valtechsd** [nuxt-community/apollo-module#401]
I am deploying my nuxt app to AWS using [this guide](https://nuxtjs.org/docs/2.x/deployment/deployment-amazon-web-services/) but I am getting what looks like an apollo related error when I generate the project. 

Below is the error I'm getting. The project otherwise finishes building but the launched page is empty (not sure if this is the reason for that, but its the only error I'm finding). Any help is much appreciated

```
ℹ Full static generation activated                                                                                                                                                           11:10:35
ℹ Generating output directory: dist/                                                                                                                                                         11:10:35
ℹ Generating pages with full static mode                                                                                                                                                     11:10:35

 ERROR   /                                                                                                                                                                                   11:10:35

TypeError: Cannot read property 'get' of undefined
    at server.js:836:38
    at apollo_module (node_modules/.cache/nuxt/apollo-module.js:35:0)
    at createApp (node_modules/.cache/nuxt/index.js:186:0)
    at async module.exports.__webpack_exports__.default (node_modules/.cache/nuxt/server.js:85:0)

✔ Client-side fallback created: 200.html                                                                                                                                                     11:10:35
```

**Comment by erik-valtechsd** [comment]
It seems  this is working now, using the following apollo setup in nuxt.config.js 

```
  apollo: {
    clientConfigs: {
      default: {
        httpEndpoint:
          process.env.HTTP_ENDPOINT || "http://localhost:1337/graphql",
        httpLinkOptions: {
          headers: {
            "x-api-key": process.env.APPSYNC_API_KEY
          }
        }
      }
    }
  },
```
