### ISSUE TITLE
Error to resolve ApolloClients

### ISSUE THREAD

**Issue by zoedsoupe** [nuxt-community/apollo-module#488]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.6.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@9.4.0`
- Builder:          `vite`
- User Config:      `apollo`, `components`, `css`, `modules`
- Runtime Modules:  `@pinia/nuxt@0.4.7`, `@nuxtjs/apollo@5.0.0-alpha.5`, `@nuxtjs/tailwindcss@6.4.1`, `@nuxt/image-edge@1.0.0-27954023.4cee565`, `nuxt-purgecss@2.0.0`, `magic-regexp/nuxt`, `nuxt-lodash@2.4.1`, `nuxt-typed-router@3.0.3`, `@vite-pwa/nuxt@0.0.6`, `nuxt-viewport@2.0.3`
- Build Modules:    `-`

### Describe the bug

I have this config at `nux.config.ts`:

```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  apollo: {
    autoImports: true,
    authType: "Bearer",
    authHeader: "Authorization",
    tokenStorage: "cookie",
    proxyCookies: true,
    clients: {
      default: {
        httpEndpoint: "https://pescarte.uenf.br/api",
      },
      local: {
        httpEndpoint: "http://localhost:4000/api",
      },
    },
  },
  // ...
});
```

and this is my setup at my login page:
```vue
<script setup lang="ts">
const query = gql`
  mutation Login($cpf: String!, $password: String!) {
    login(cpf: $cpf, password: $password) {
      token
      user {
        id
        birthdate
        firstName
        middleName
        lastName
        cpf
        role
      }
    }
  }
`;

const { mutate: login } = useMutation<Login>(query, { clientId: "local" });

async function handleSubmit(values) {
  const { onLogin } = useApollo();
  const { cpf, password } = values;

  const variables = { cpf, password };

  const result = await login(variables);

  console.log(result);
}
</script>
```

However when the login form is submitted, it occurs this error:
`Uncaught (in promise) Error: No apolloClients injection found, tried to resolve 'local' clientId`

### Expected behaviour

ApolloClient should be resolved and queries/mutations executed normally

### Additional context

If I try to use the `default` ApolloClient it also fails with the same error.

The whole code can be found at: https://github.com/peapescarte/plataforma

### Logs

```shell
useApolloClient.ts:27 
        
       Uncaught (in promise) Error: No apolloClients injection found, tried to resolve 'local' clientId
    at resolveClientWithId (useApolloClient.ts:27:11)
    at resolveImpl (useApolloClient.ts:51:24)
    at resolveClient (useApolloClient.ts:66:20)
    at mutate (useMutation.ts:78:20)
    at handleSubmit (acessar.vue:69:3)
    at vee-validate.js:1802:1
resolveClientWithId @ useApolloClient.ts:27
resolveImpl @ useApolloClient.ts:51
resolveClient @ useApolloClient.ts:66
mutate @ useMutation.ts:78
handleSubmit @ acessar.vue:69
(anonymous) @ vee-validate.js:1802
Promise.catch (async)
callWithAsyncErrorHandling @ chunk-3NMN3MUW.js:1590
invoker @ chunk-3NMN3MUW.js:8198

```
```

**Comment by zoedsoupe** [comment]
Noticed that this address #444
