### ISSUE TITLE
Relative API url doesn't work with SSR

### ISSUE THREAD

**Issue by filiphazardous** [nuxt-community/apollo-module#610]
### Environment

- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.10.3
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  pnpm@8.15.4
- Builder:          -
- User Config:      experimental, debug, ssr, css, formkit, components, modules, typescript, runtimeConfig, vite, nitro, tailwindcss, i18n, headlessui, apollo, unionen-apollo-codegen, graphqlServer, primevue, pinia, hooks, build
- Runtime Modules:  @formkit/nuxt@1.6.0, @formkit/auto-animate/nuxt@0.8.1, @nuxtjs/i18n@8.1.1, @nuxtjs/tailwindcss@6.11.4, nuxt-headlessui@1.1.5, nuxt-primevue@0.3.1, @nuxtjs/apollo@5.0.0-alpha.14, nuxt-graphql-server@3.0.0, @nuxt/test-utils/module@3.12.0, @pinia/nuxt@0.5.1, @nuxtjs/google-fonts@3.2.0
- Build Modules:    -

### Describe the bug

I have a graphql resolver in the server portion of Nuxt, and its endpoint stored in an env variable. It works nicely when called from the client, but blows up when called on the server side.

It is possible to work around this by supplying the full URL in the env variable, but this is impractical for scenarios where I need the environment to answer to multiple domain names.

### Expected behaviour

I would expect to be able to call the local endpoint.

### Logs

```shell
`{
  operation: {
    variables: { language: 'sv' },
    extensions: {},
    operationName: 'schoolOptions',
    query: { kind: 'Document', definitions: [Array], loc: [Location] }
  },
  networkError: TypeError: Failed to parse URL from /api/nuxt/graphql
      at Object.fetch (node:internal/deps/undici/undici:11576:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
        at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
        at new NodeError (node:internal/errors:405:5)
        at new URL (node:internal/url:611:13)
        at new Request (node:internal/deps/undici/undici:7132:25)
        at fetch2 (node:internal/deps/undici/undici:10715:25)
        at Object.fetch (node:internal/deps/undici/undici:11574:18)
        at fetch (node:internal/process/pre_execution:229:25)
        at /home/filip/weahead/digitalist/unionen/frontend/node_modules/.pnpm/@nuxtjs+apollo@5.0.0-alpha.14_rollup@4.13.0_typescript@5.4.3_vue@3.4.21/node_modules/@apollo/client/link/http/createHttpLink.js:120:7
        at new Subscription (/home/filip/weahead/digitalist/unionen/frontend/node_modules/.pnpm/zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:197:34)
        at Observable.subscribe (/home/filip/weahead/digitalist/unionen/frontend/node_modules/.pnpm/zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:279:14)
        at /home/filip/weahead/digitalist/unionen/frontend/node_modules/.pnpm/@nuxtjs+apollo@5.0.0-alpha.14_rollup@4.13.0_typescript@5.4.3_vue@3.4.21/node_modules/@apollo/client/link/context/index.js:20:45
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      input: '/api/nuxt/graphql',
      code: 'ERR_INVALID_URL'
    }
  },
  graphQLErrors: undefined,
  forward: [Function (anonymous)]
}`
```

**Comment by pixleight** [comment]
Also interested in this. Seems to be related (or duplicate?) of #507 , so this appears to have been an issue for quite some time.
